### ISSUE TITLE
[maven-update] Unrecognised tag: 'target.jdk' in apt/pom.xml

### ISSUE THREAD

**Issue by dwtj** [dwtj/panini#1]
Build fails on commit 8f7af8f58956b0d2315c9558c34b252a8796dcc9 when to attempting perform either `mvn install` or `mvn clean` from the `org.paninij/` directory:

```
[ERROR]     Malformed POM /Users/owl/Projects/panini/org.paninij/apt/pom.xml: Unrecognised tag: 'target.jdk' (position: START_TAG seen ...</artifactId>\n\n  <target.jdk>... @13:15)  @ /Users/owl/Projects/panini/org.paninij/apt/pom.xml, line 13, column 15 -> [Help 2]
```

Here's my `mvn --version` info:

```
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T11:29:23-06:00)
Maven home: /usr/local/Cellar/maven/3.2.5/libexec
Java version: 1.8.0_05, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.2", arch: "x86_64", family: "mac"
```

For now, I've just commented out the offending tag from `org.paninij/apt/pom.xml`. Do we need this tag in here? *Can we just get rid of it?* Is the target/source info inside of `org.paninij/pom.xml` enough?

**Comment by kristinclemens** [comment]
That's correct. Not sure how one of those got stuck in there! I'll check it out real quick and double-check just to make sure.

**Comment by kristinclemens** [comment]
This is fixed in commit https://github.com/dwtj/panini/commit/8f7af8f58956b0d2315c9558c34b252a8796dcc9
