### ISSUE TITLE
[Pre-RFC] Duck Futures

### ISSUE THREAD

**Issue by dwtj** [dwtj/panini#11]
I wrote up some of my current understanding and current thoughts of how we should implement Duck Futures. It's up on the [wiki](https://github.com/dwtj/panini/wiki/Duck-Futures-RFC) now. I wanted to hear back from you guys before adding duck code to `generated-src/expected` to the repo, since these ideas here aren't yet fully-baked. Let me know what you guys think, especially the `Object$Duck$String$int` example.

**Comment by dwtj** [comment]
Note that I added an image for what I'm thinking the inheritance might look like.

**Comment by kristinclemens** [comment]
Can this be cleaned up, David?

**Comment by kristinclemens** [comment]
And by that I mean, closed if it is done.

**Comment by dwtj** [comment]
This is meant to be a place for general discussion on the design of Duck futures. We are still implementing duck futures at the moment, so I think that it should stay open for now.
