### ISSUE TITLE
Generated Ducks do not have the null check in .equals that the panc ducks possess

### ISSUE THREAD

**Issue by TErenberger** [dwtj/panini#18]
```
@Override
    public boolean equals(Object arg0) {
        return panini$get().equals(arg0);
    }
```
is what the generated ducks currently have for the .equals method. In panc this method is treated as a special case changed to be:

```
Object.equals(Object o) {
    if(this.get() == null) return o == null; else return this.get().equals(o);
}
```
The panc version may have problems as noted in another issue, but ours will cause a null pointer exception exception if panini$get() returns a null which is a bigger issue that the other.

**Comment by kristinclemens** [comment]
Status of this? @TErenberger

**Comment by dwtj** [comment]
The last I checked, Trey sent an email to Rajan which was forwarded to Eric Lin, and we haven't heard anything back.

**Comment by kristinclemens** [comment]
Should we apply a temporary fix and leave the issue open? This is probably something I will wind up checking in tests.

**Comment by TErenberger** [comment]
above the pay grade boss

**Comment by dwtj** [comment]
I don't think that we really know what a "temporary fix" would be in this case. They implemented support for this special case in `panc` for some reason, but we don't know why exactly. Their solution looks a bit fishy, as discussed in issue #12.

We're definitely going to need to come back to both of these issues and figure them out at some point. I say leave it alone for now and leave the issue open until we find out more about what `panc` is doing and we understand the problem better.

**Comment by kristinclemens** [comment]
Aaaallllriiiighty theeeeeen!

**Comment by kristinclemens** [comment]
Also, Trey, that was 100% inappropriate.

jkjk <3

**Comment by kristinclemens** [comment]
I'm going to close this as a duplicate then.
