### ISSUE TITLE
[maven-update] Instructions on setting up development environment.

### ISSUE THREAD

**Issue by dwtj** [dwtj/panini#2]
As of 8f7af8f58956b0d2315c9558c34b252a8796dcc9 (Kristin's recent work on the maven-update branch), I know how to set up a command-line based development environment, but it is unclear to me how to set up a development environment within Eclipse. I tried a few ways of importing a fresh git clone into eclipse as a maven project, but it seemed like I was just making a new maven project rather than using `org.paninij/pom.xml`.

Could we make a very basic walkthrough on the wiki describing how to do this (and try to keep it up to date)?

**Comment by kristinclemens** [comment]
Not a problem. For now, it's as simple as, roughly:

From a fresh git clone, `cd` in to your `org.paninij` folder. This is the location of the top-level pom.xml. From there, run `mvn clean install` then `mvn eclipse:eclipse`.

Then go in to eclipse and import your freshly created maven projects!

**Comment by kristinclemens** [comment]
Will get a wiki up within the next two days. Any idea where it should go?

**Comment by dwtj** [comment]
Here's a wiki page that we could use: [link](https://github.com/dwtj/panini/wiki/Setting-Up-Eclipse-Development-Environment)

**Comment by ddmills** [comment]
https://github.com/hridesh/panini/wiki/Setting-Up-the-Development-Environment-(Eclipse)
