### ISSUE TITLE
Capsule Procedure IDs cannot be ambiguous

### ISSUE THREAD

**Issue by ddmills** [dwtj/panini#21]
Generated capsule ID's are currently namespaced, but variables cannot contain periods, so they get replaced with underscores "_". Arrays variables (that end with brackets "[]" also need to be replaced, and are currently replaced with "Array". However, these names can still be ambiguous since a classname could potentially collide with the auto generated IDs.

Once solution would be to trash the named ID's and just put integers everywhere.

**Comment by kristinclemens** [comment]
Serialization, in a sense? I don't fully understand how serialization works, but I do know that when I create class that extends some sort of Generic Collection Java yells at me to serialize it. Just a thought.

**Comment by dwtj** [comment]
It is somewhat similar to serialization in the sense that we are defining an unambiguous encoding for things, however we will need to define the encoding logic ourselves somehow (i.e. I don't see Java Serialization mechanism being directly useful).

**Comment by ddmills** [comment]
https://github.com/hridesh/panini/issues/10
