### ISSUE TITLE
`Source.format()` does not substitute item for last format element

### ISSUE THREAD

**Issue by dwtj** [dwtj/panini#24]
There is a bug in the logic of `Source.format()` such that an item is not included in the returned `String` for the last format element in a format string when this format element is at the very end of the format string.

One simple case which fails is

``` java
Source.format("#0 != #1", "foo", "bar");
```

This case will erroneously return the `String` `"foo != "`, though it should have returned `"foo != bar"`.

Until this is fixed, one can often work-around this bug in the context of source generation by adding whitespace after last format element.

**Comment by kristinclemens** [comment]
I'll take a quick look at this. It's probably something fairly simple, and since I haven't looked at this code before I might be able to catch it more easily than you.

**Comment by kristinclemens** [comment]
@dwtj Which branch is this in? capsule-generation/master? Could you link a commit?

**Comment by dwtj** [comment]
It has been around since `Source.format()` was first implemented (a long time ago now). Either `[master]` or `[capsule-generation/master]` would be a decent place to fix it or to branch from in order to fix it.

I have a rough idea of the problem: in the above described case, the finite state machine which is used to process the format string does not transition *out* of the `HASH_NUM` state and insert the right string.

There may be a similar problem in a different case: when a format string ends with a `#` character, that `#` character may not be added to the final string.

One idea for a quick fix that would keep the FSM transition logic close to what it is currently, the implementation could just append a whitespace character to the format string *for processing* and then just drop that whitespace character before the result is returned to the user. Essentially, we do the workaround described in the original post in a way which is transparent to the user.

**Comment by dwtj** [comment]
Come to think of it, it is probably best to make a branch rather than doing it directly on one of the `master` branches.

**Comment by kristinclemens** [comment]
Sounds good! I have to head down to Des Moines now but will continue looking at this when I get home.

**Comment by dwtj** [comment]
Resolved by commit 5d951c63d8f0d50f12d484257b1148bc28240f48.
