### ISSUE TITLE
[capsule-generation/aligned] formatAligned: fmt string must have at least one character after '##'

### ISSUE THREAD

**Issue by TErenberger** [dwtj/panini#32]
The function uses String.split() to hold the two halves of the format string around the '##'. If there is not space after the '##' the result array from split will only contain one element which will cause a index out of bounds exception when the split[1] concatenated to the string.

The current workaround is to add a space after the flag or use the Source.lines(0, "##") for input fmt.

**Comment by TErenberger** [comment]
A possible solution is storing each half as a string initially and appending the #0... #x flags to the front string. Then after the loop, appending the back string. This way no arrays are used and no index out of bounds error will occur.

**Comment by dwtj** [comment]
Resolved as of commit d8e9a115e3029b125eb3955e9a472a2be3ce9782.
