### ISSUE TITLE
Rename Project To @PaniniJ

### ISSUE THREAD

**Issue by dwtj** [dwtj/panini#36]
Anything named `PaniniPress` should be changed to `@PaniniJ`. This will affect the `PaniniPress` annotation processor class and maybe some maven-related configuration.

Note that when the `PaniniPress` class name is changed, the capsule-generation project's service file will also need to be changed.

**Comment by dwtj** [comment]
As of commit fffcdb0b04973840bbcf09a3028fe819b78597fe, `PaniniPress` has been renamed to `PaniniProcessor`.

**Comment by ddmills** [comment]
https://github.com/hridesh/panini/issues/13
